services:
  elasticsearch:
    image: elasticsearch:8.13.0
    restart: always
    # Я оставил порты наружу для ES только для того чтобы можно было запустить тесты для проекта)
    # Спасибо большое за статью!
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - 9200
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 10s
      retries: 50
  
  # Вместо кибаны я использовал elasticvue, в dev compose файле есть для этого настройки,
  # в следующий раз попробую кибану, спасибо за рекомендацию!

  db:
    build: ./db
    restart: always
    env_file:
      - .env
    volumes:
      - movies-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build: .
    restart: always
    env_file:
      - ./etl/.env
    volumes:
      - state:/opt/etl/state
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  esdata:
  movies-data:
  state: